// Code generated by ent, DO NOT EDIT.

package quiz

const (
	// Label holds the string label denoting the quiz type in the database.
	Label = "quiz"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the quiz in the database.
	Table = "quizs"
)

// Columns holds all SQL columns for quiz fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
