// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bkRyusim/quizlog-go/ent/predicate"
	"github.com/bkRyusim/quizlog-go/ent/quiz"
	"github.com/bkRyusim/quizlog-go/ent/user"
)

// QuizUpdate is the builder for updating Quiz entities.
type QuizUpdate struct {
	config
	hooks    []Hook
	mutation *QuizMutation
}

// Where appends a list predicates to the QuizUpdate builder.
func (qu *QuizUpdate) Where(ps ...predicate.Quiz) *QuizUpdate {
	qu.mutation.Where(ps...)
	return qu
}

// SetPostUrl sets the "postUrl" field.
func (qu *QuizUpdate) SetPostUrl(s string) *QuizUpdate {
	qu.mutation.SetPostUrl(s)
	return qu
}

// SetQuestion sets the "question" field.
func (qu *QuizUpdate) SetQuestion(s string) *QuizUpdate {
	qu.mutation.SetQuestion(s)
	return qu
}

// SetAnswer sets the "answer" field.
func (qu *QuizUpdate) SetAnswer(s string) *QuizUpdate {
	qu.mutation.SetAnswer(s)
	return qu
}

// SetCreatedAt sets the "createdAt" field.
func (qu *QuizUpdate) SetCreatedAt(t time.Time) *QuizUpdate {
	qu.mutation.SetCreatedAt(t)
	return qu
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (qu *QuizUpdate) SetNillableCreatedAt(t *time.Time) *QuizUpdate {
	if t != nil {
		qu.SetCreatedAt(*t)
	}
	return qu
}

// SetUpdatedAt sets the "updatedAt" field.
func (qu *QuizUpdate) SetUpdatedAt(t time.Time) *QuizUpdate {
	qu.mutation.SetUpdatedAt(t)
	return qu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (qu *QuizUpdate) SetUserID(id int) *QuizUpdate {
	qu.mutation.SetUserID(id)
	return qu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (qu *QuizUpdate) SetNillableUserID(id *int) *QuizUpdate {
	if id != nil {
		qu = qu.SetUserID(*id)
	}
	return qu
}

// SetUser sets the "user" edge to the User entity.
func (qu *QuizUpdate) SetUser(u *User) *QuizUpdate {
	return qu.SetUserID(u.ID)
}

// Mutation returns the QuizMutation object of the builder.
func (qu *QuizUpdate) Mutation() *QuizMutation {
	return qu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (qu *QuizUpdate) ClearUser() *QuizUpdate {
	qu.mutation.ClearUser()
	return qu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (qu *QuizUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	qu.defaults()
	if len(qu.hooks) == 0 {
		affected, err = qu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QuizMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qu.mutation = mutation
			affected, err = qu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(qu.hooks) - 1; i >= 0; i-- {
			if qu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = qu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (qu *QuizUpdate) SaveX(ctx context.Context) int {
	affected, err := qu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (qu *QuizUpdate) Exec(ctx context.Context) error {
	_, err := qu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qu *QuizUpdate) ExecX(ctx context.Context) {
	if err := qu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qu *QuizUpdate) defaults() {
	if _, ok := qu.mutation.UpdatedAt(); !ok {
		v := quiz.UpdateDefaultUpdatedAt()
		qu.mutation.SetUpdatedAt(v)
	}
}

func (qu *QuizUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   quiz.Table,
			Columns: quiz.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: quiz.FieldID,
			},
		},
	}
	if ps := qu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := qu.mutation.PostUrl(); ok {
		_spec.SetField(quiz.FieldPostUrl, field.TypeString, value)
	}
	if value, ok := qu.mutation.Question(); ok {
		_spec.SetField(quiz.FieldQuestion, field.TypeString, value)
	}
	if value, ok := qu.mutation.Answer(); ok {
		_spec.SetField(quiz.FieldAnswer, field.TypeString, value)
	}
	if value, ok := qu.mutation.CreatedAt(); ok {
		_spec.SetField(quiz.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := qu.mutation.UpdatedAt(); ok {
		_spec.SetField(quiz.FieldUpdatedAt, field.TypeTime, value)
	}
	if qu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.UserTable,
			Columns: []string{quiz.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.UserTable,
			Columns: []string{quiz.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, qu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quiz.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// QuizUpdateOne is the builder for updating a single Quiz entity.
type QuizUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuizMutation
}

// SetPostUrl sets the "postUrl" field.
func (quo *QuizUpdateOne) SetPostUrl(s string) *QuizUpdateOne {
	quo.mutation.SetPostUrl(s)
	return quo
}

// SetQuestion sets the "question" field.
func (quo *QuizUpdateOne) SetQuestion(s string) *QuizUpdateOne {
	quo.mutation.SetQuestion(s)
	return quo
}

// SetAnswer sets the "answer" field.
func (quo *QuizUpdateOne) SetAnswer(s string) *QuizUpdateOne {
	quo.mutation.SetAnswer(s)
	return quo
}

// SetCreatedAt sets the "createdAt" field.
func (quo *QuizUpdateOne) SetCreatedAt(t time.Time) *QuizUpdateOne {
	quo.mutation.SetCreatedAt(t)
	return quo
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (quo *QuizUpdateOne) SetNillableCreatedAt(t *time.Time) *QuizUpdateOne {
	if t != nil {
		quo.SetCreatedAt(*t)
	}
	return quo
}

// SetUpdatedAt sets the "updatedAt" field.
func (quo *QuizUpdateOne) SetUpdatedAt(t time.Time) *QuizUpdateOne {
	quo.mutation.SetUpdatedAt(t)
	return quo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (quo *QuizUpdateOne) SetUserID(id int) *QuizUpdateOne {
	quo.mutation.SetUserID(id)
	return quo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (quo *QuizUpdateOne) SetNillableUserID(id *int) *QuizUpdateOne {
	if id != nil {
		quo = quo.SetUserID(*id)
	}
	return quo
}

// SetUser sets the "user" edge to the User entity.
func (quo *QuizUpdateOne) SetUser(u *User) *QuizUpdateOne {
	return quo.SetUserID(u.ID)
}

// Mutation returns the QuizMutation object of the builder.
func (quo *QuizUpdateOne) Mutation() *QuizMutation {
	return quo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (quo *QuizUpdateOne) ClearUser() *QuizUpdateOne {
	quo.mutation.ClearUser()
	return quo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (quo *QuizUpdateOne) Select(field string, fields ...string) *QuizUpdateOne {
	quo.fields = append([]string{field}, fields...)
	return quo
}

// Save executes the query and returns the updated Quiz entity.
func (quo *QuizUpdateOne) Save(ctx context.Context) (*Quiz, error) {
	var (
		err  error
		node *Quiz
	)
	quo.defaults()
	if len(quo.hooks) == 0 {
		node, err = quo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QuizMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			quo.mutation = mutation
			node, err = quo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(quo.hooks) - 1; i >= 0; i-- {
			if quo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = quo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, quo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Quiz)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from QuizMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (quo *QuizUpdateOne) SaveX(ctx context.Context) *Quiz {
	node, err := quo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (quo *QuizUpdateOne) Exec(ctx context.Context) error {
	_, err := quo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (quo *QuizUpdateOne) ExecX(ctx context.Context) {
	if err := quo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (quo *QuizUpdateOne) defaults() {
	if _, ok := quo.mutation.UpdatedAt(); !ok {
		v := quiz.UpdateDefaultUpdatedAt()
		quo.mutation.SetUpdatedAt(v)
	}
}

func (quo *QuizUpdateOne) sqlSave(ctx context.Context) (_node *Quiz, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   quiz.Table,
			Columns: quiz.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: quiz.FieldID,
			},
		},
	}
	id, ok := quo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Quiz.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := quo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quiz.FieldID)
		for _, f := range fields {
			if !quiz.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quiz.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := quo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := quo.mutation.PostUrl(); ok {
		_spec.SetField(quiz.FieldPostUrl, field.TypeString, value)
	}
	if value, ok := quo.mutation.Question(); ok {
		_spec.SetField(quiz.FieldQuestion, field.TypeString, value)
	}
	if value, ok := quo.mutation.Answer(); ok {
		_spec.SetField(quiz.FieldAnswer, field.TypeString, value)
	}
	if value, ok := quo.mutation.CreatedAt(); ok {
		_spec.SetField(quiz.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := quo.mutation.UpdatedAt(); ok {
		_spec.SetField(quiz.FieldUpdatedAt, field.TypeTime, value)
	}
	if quo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.UserTable,
			Columns: []string{quiz.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.UserTable,
			Columns: []string{quiz.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Quiz{config: quo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, quo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quiz.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
