// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/bkRyusim/quizlog-go/ent/quiz"
)

// Quiz is the model entity for the Quiz schema.
type Quiz struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Quiz) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quiz.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Quiz", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Quiz fields.
func (q *Quiz) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quiz.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			q.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Quiz.
// Note that you need to call Quiz.Unwrap() before calling this method if this Quiz
// was returned from a transaction, and the transaction was committed or rolled back.
func (q *Quiz) Update() *QuizUpdateOne {
	return (&QuizClient{config: q.config}).UpdateOne(q)
}

// Unwrap unwraps the Quiz entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (q *Quiz) Unwrap() *Quiz {
	_tx, ok := q.config.driver.(*txDriver)
	if !ok {
		panic("ent: Quiz is not a transactional entity")
	}
	q.config.driver = _tx.drv
	return q
}

// String implements the fmt.Stringer.
func (q *Quiz) String() string {
	var builder strings.Builder
	builder.WriteString("Quiz(")
	builder.WriteString(fmt.Sprintf("id=%v", q.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Quizs is a parsable slice of Quiz.
type Quizs []*Quiz

func (q Quizs) config(cfg config) {
	for _i := range q {
		q[_i].config = cfg
	}
}
