// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bkRyusim/quizlog-go/ent/quiz"
	"github.com/bkRyusim/quizlog-go/ent/user"
)

// QuizCreate is the builder for creating a Quiz entity.
type QuizCreate struct {
	config
	mutation *QuizMutation
	hooks    []Hook
}

// SetPostUrl sets the "postUrl" field.
func (qc *QuizCreate) SetPostUrl(s string) *QuizCreate {
	qc.mutation.SetPostUrl(s)
	return qc
}

// SetQuestion sets the "question" field.
func (qc *QuizCreate) SetQuestion(s string) *QuizCreate {
	qc.mutation.SetQuestion(s)
	return qc
}

// SetAnswer sets the "answer" field.
func (qc *QuizCreate) SetAnswer(s string) *QuizCreate {
	qc.mutation.SetAnswer(s)
	return qc
}

// SetCreatedAt sets the "createdAt" field.
func (qc *QuizCreate) SetCreatedAt(t time.Time) *QuizCreate {
	qc.mutation.SetCreatedAt(t)
	return qc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (qc *QuizCreate) SetNillableCreatedAt(t *time.Time) *QuizCreate {
	if t != nil {
		qc.SetCreatedAt(*t)
	}
	return qc
}

// SetUpdatedAt sets the "updatedAt" field.
func (qc *QuizCreate) SetUpdatedAt(t time.Time) *QuizCreate {
	qc.mutation.SetUpdatedAt(t)
	return qc
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (qc *QuizCreate) SetNillableUpdatedAt(t *time.Time) *QuizCreate {
	if t != nil {
		qc.SetUpdatedAt(*t)
	}
	return qc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (qc *QuizCreate) SetUserID(id int) *QuizCreate {
	qc.mutation.SetUserID(id)
	return qc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (qc *QuizCreate) SetNillableUserID(id *int) *QuizCreate {
	if id != nil {
		qc = qc.SetUserID(*id)
	}
	return qc
}

// SetUser sets the "user" edge to the User entity.
func (qc *QuizCreate) SetUser(u *User) *QuizCreate {
	return qc.SetUserID(u.ID)
}

// Mutation returns the QuizMutation object of the builder.
func (qc *QuizCreate) Mutation() *QuizMutation {
	return qc.mutation
}

// Save creates the Quiz in the database.
func (qc *QuizCreate) Save(ctx context.Context) (*Quiz, error) {
	var (
		err  error
		node *Quiz
	)
	qc.defaults()
	if len(qc.hooks) == 0 {
		if err = qc.check(); err != nil {
			return nil, err
		}
		node, err = qc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QuizMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = qc.check(); err != nil {
				return nil, err
			}
			qc.mutation = mutation
			if node, err = qc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(qc.hooks) - 1; i >= 0; i-- {
			if qc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = qc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, qc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Quiz)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from QuizMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (qc *QuizCreate) SaveX(ctx context.Context) *Quiz {
	v, err := qc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qc *QuizCreate) Exec(ctx context.Context) error {
	_, err := qc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qc *QuizCreate) ExecX(ctx context.Context) {
	if err := qc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qc *QuizCreate) defaults() {
	if _, ok := qc.mutation.CreatedAt(); !ok {
		v := quiz.DefaultCreatedAt()
		qc.mutation.SetCreatedAt(v)
	}
	if _, ok := qc.mutation.UpdatedAt(); !ok {
		v := quiz.DefaultUpdatedAt()
		qc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qc *QuizCreate) check() error {
	if _, ok := qc.mutation.PostUrl(); !ok {
		return &ValidationError{Name: "postUrl", err: errors.New(`ent: missing required field "Quiz.postUrl"`)}
	}
	if _, ok := qc.mutation.Question(); !ok {
		return &ValidationError{Name: "question", err: errors.New(`ent: missing required field "Quiz.question"`)}
	}
	if _, ok := qc.mutation.Answer(); !ok {
		return &ValidationError{Name: "answer", err: errors.New(`ent: missing required field "Quiz.answer"`)}
	}
	if _, ok := qc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Quiz.createdAt"`)}
	}
	if _, ok := qc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Quiz.updatedAt"`)}
	}
	return nil
}

func (qc *QuizCreate) sqlSave(ctx context.Context) (*Quiz, error) {
	_node, _spec := qc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (qc *QuizCreate) createSpec() (*Quiz, *sqlgraph.CreateSpec) {
	var (
		_node = &Quiz{config: qc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: quiz.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: quiz.FieldID,
			},
		}
	)
	if value, ok := qc.mutation.PostUrl(); ok {
		_spec.SetField(quiz.FieldPostUrl, field.TypeString, value)
		_node.PostUrl = value
	}
	if value, ok := qc.mutation.Question(); ok {
		_spec.SetField(quiz.FieldQuestion, field.TypeString, value)
		_node.Question = value
	}
	if value, ok := qc.mutation.Answer(); ok {
		_spec.SetField(quiz.FieldAnswer, field.TypeString, value)
		_node.Answer = value
	}
	if value, ok := qc.mutation.CreatedAt(); ok {
		_spec.SetField(quiz.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := qc.mutation.UpdatedAt(); ok {
		_spec.SetField(quiz.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := qc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quiz.UserTable,
			Columns: []string{quiz.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_quiz = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuizCreateBulk is the builder for creating many Quiz entities in bulk.
type QuizCreateBulk struct {
	config
	builders []*QuizCreate
}

// Save creates the Quiz entities in the database.
func (qcb *QuizCreateBulk) Save(ctx context.Context) ([]*Quiz, error) {
	specs := make([]*sqlgraph.CreateSpec, len(qcb.builders))
	nodes := make([]*Quiz, len(qcb.builders))
	mutators := make([]Mutator, len(qcb.builders))
	for i := range qcb.builders {
		func(i int, root context.Context) {
			builder := qcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuizMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qcb *QuizCreateBulk) SaveX(ctx context.Context) []*Quiz {
	v, err := qcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qcb *QuizCreateBulk) Exec(ctx context.Context) error {
	_, err := qcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qcb *QuizCreateBulk) ExecX(ctx context.Context) {
	if err := qcb.Exec(ctx); err != nil {
		panic(err)
	}
}
