// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blog is the predicate function for blog builders.
type Blog func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Quiz is the predicate function for quiz builders.
type Quiz func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
